import React from "react";
import Head from "next/head";

import style from "../styles/mobile.module.css";

// import components
import NavigationBar from "./navigationBar";

const Layout = ({ title, children }) => {
  return (
    <div className='container h-screen min-h-screen max-h-screen mx-auto max-w-xl relative'>
      <Head className='h-10'>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='mb-auto h-full overflow-auto no-scrollbar'>
        {children}
      </main>
      <div
        className='mt-auto h-14 absolute bottom-0 w-full'
        style={{ backgroundColor: "blue" }}
      >
        <NavigationBar />
      </div>
    </div>
  );
};

export default Layout;
